title = "ç´«é¾™ä¼ åª’"
baseURL = "https://zlon.com.cn/"
theme = "bilberry-hugo-theme"
publishDir = "docs"
# zlonmedia_sites_images token: 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

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "zh-cn"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "G-ZHYDNF0MJL"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "ZlonMedia"
  description = "Tianjin Zlon Culture Media Co., Ltd."
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "0I9UFG7RSM"
  algolia_apiKey    = "d460fd67695166b2cbedc12c8d5292a2"
  algolia_indexName = "dev_zlonmedia"
  # Set this option to false if you want to search within all articles in all languages at once
  algolia_currentLanguageOnly = false

  # Enable / Disable comments on the articles via commento
  # commentoJsURL = "https://commento.lednerb.de/js/commento.js"

  # Enable / Disable Giscus comments
  giscus             = true
  giscusJsUrl        = "https://giscus.app/client.js"
  giscusRepository   = "forangh/grape.github.io"
  giscusRepositoryId = "R_kgDOIFdTyw"
  giscusMapping      = "pathname"
  giscusCategory     = "General"
  giscusCategoryId   = "DIC_kwDOIFdTy84CSBlF"
  data-strict        = "0"
  data-reactions-enabled = "1"
  data-input-position= "bottom"
  giscusTheme        = "light"
  giscusReactions    = "1"
  giscusEmitMetadata = "0"
  giscusLanguage     = "zh-CN"
  giscusCrossOrigin  = "anonymous"

  # Enable / Disable Utterances comments
  utterances            = false
  utterancesJsUrl       = "https://utteranc.es/client.js"
  utterancesRepository  = "[ENTER REPO HERE]"
  utterancesIssueTerm   = "pathname"
  utterancesLabel       = "Comment"
  utterancesTheme       = "github-light"
  utterancesCrossOrigin = "anonymous"

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "ZlonMedia"

    # if you want to use libravatar or gravatar for the header image
    avatarEmail = ""

    # set an path to the image file you want to use | overwrites avatar by email
    customImage = "mypicture/zlonicon1.png"

    # define the icon you want to use for the overlay for the customImage or avatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = false

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "content/page/about/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = true

    # enable automatic localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = false

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 400

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 3

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 3

    # show a language chooser in the footer
    showFooterLanguageChooser = false

    # social media profile urls for the footer links
    showSocialMedia = true

    # show an archive link in the footer
    showArchive = true

    # archive grouping: "2006" by year, "2006-01" by month
    archiveDateGrouping = "2006-01"

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://www.bitechan.mobi/zh-CN/register?ref=JKZCKM15&registerChannel=goose", icon = "fab fa-bitcoin" },
      { link = "https://twitter.com/zlonmedia", icon = "fab fa-twitter" },
      { link = "https://t.me/zlonmedia", icon = "fab fa-telegram" },
      { link = "https://github.com/metatopnews", icon = "fab fa-github" },
      { link = "https://weibo.com/u/7083325518", icon = "fab fa-weibo" },
      { link = "https://www.douyin.com/user/MS4wLjABAAAAhktK3OAfxIpP-u_jSB-GBfPq46CPBxEMNDGPOsPkiPI", icon = "fab fa-tiktok" },
      
    ]

    # credits line configuration
    copyrightBy = "by ZlonMedia"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2017"
    copyrightUrl = "https://zlon.com.cn"
    creditsText = "æ´¥ICPå¤‡19002933å·-1"
    creditsUrl = "https://beian.miit.gov.cn/"


# customize your available languages for your multi-lingual site
# or delete one of the [Languages.xx] blocks to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1
  [Languages.zh-cn]
    weight = 2
    title = "ğŸ…©ğŸ…›ğŸ…ğŸ… ç´«é¾™ä¼ åª’"
    subtitle = "ğŸ…œğŸ…”ğŸ…“ğŸ…˜ğŸ… #â„•ğ”½ğ•‹ ğŸ…’ğŸ…˜ğŸ…ğŸ…”ğŸ…œğŸ… #ğ•â„"

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Change to 'true' if you need to render raw HTML within your markdown content
      unsafe = true

  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2
